version: '3'
services:
  configserver:
    build:
      context: ./config-server
    ports:
      - "8888:8888"
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8060:8060"
  nameserver:
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
  customer-portal:
    build:
      context: ./billing/customer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MJ_APIKEY_PUBLIC
      - MJ_APIKEY_PRIVATE
      - CONFIG_SERVER=configserver
      - DISCOVERY_SERVER=nameserver
    depends_on:
      - configserver
      - nameserver
  product-portal:
    build:
      context: ./billing/product-portal
    ports:
      - "8070:8070"
    environment:
      - CONFIG_SERVER=configserver
      - DISCOVERY_SERVER=nameserver
    depends_on:
      - configserver
      - nameserver
  order-portal:
    build:
      context: ./billing/order-portal
    ports:
      - "8090:8090"
    environment:
      - CONFIG_SERVER=configserver
      - DISCOVERY_SERVER=nameserver
      - CUSTOMER_PORTAL_URL=customer-portal
      - CUSTOMER_PORTAL_PORT=8080
      - PRODUCT_PORTAL_URL=product-portal
      - PRODUCT_PORTAL_PORT=8070
    depends_on:
      - configserver
      - nameserver

