apiVersion: v1
kind: Service
metadata:
  name: discovery-server-cluster-ip
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30003
  selector:
    component: discovery-server